AWSTemplateFormatVersion: 2010-09-09
Description: |
  This templates launches an ec2 instance which enables SSH.
  
Resources:
  ABE:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-0022f774911c1d690 
        InstanceType: t2.micro
        KeyName: firstkey
        SecurityGroups:
        - Project-101-kittens-carousel-static-website-ec2-SSH-HTTPS-HTTP-ALL
        Tags:
        - Key: Name
          Value: Project-101-kittens-carousel-static-website-ec2-SSH-HTTPS-HTTP-ALL
        UserData:
          Fn::Base64: 
            !Sub |
              #!/bin/bash
              yum update -y
              yum install -y httpd.x86_64
                           
              cd /var/www/html/
              wget https://raw.githubusercontent.com/deepvirtualdoubts/101-kittens-carousel-static-website-ec2/main/static-web/index.html
              wget https://raw.githubusercontent.com/deepvirtualdoubts/101-kittens-carousel-static-website-ec2/main/static-web/cat0.jpg
              wget https://raw.githubusercontent.com/deepvirtualdoubts/101-kittens-carousel-static-website-ec2/main/static-web/cat1.jpg
              wget https://raw.githubusercontent.com/deepvirtualdoubts/101-kittens-carousel-static-website-ec2/main/static-web/cat2.jpg
              wget https://raw.githubusercontent.com/deepvirtualdoubts/101-kittens-carousel-static-website-ec2/main/static-web/cat3.jpg
              
              systemctl start httpd.service
              systemctl enable httpd.service

Outputs:
  WebsiteURL:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt ABE.PublicDnsName
    Description: Kittens Carousel Application URL           
              
              


      
